name: tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and run tests
        run: |
          cd auth
          npm install
          npm run test:ci
