name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and run tests
        run: |
          cd orders
          npm install
          npm run test:ci
